### ISSUE TITLE
User Epic

### ISSUE THREAD

**Issue by epicallan** [freelyformd/eval-cso#5]
User [Epic](https://www.atlassian.com/agile/project-management/epics) expectations

- [ ] should have a login form @lubegasimon 
- [ ] should have a signup form @brian-seruwuge 
- [ ] user profile section sidebar should have sign out button
- [ ] should have an editable profile page @aleku399 
- [ ] should have a user table with editable user fields by admin. @aleku399 
- [ ] login form container 
- [ ] signup form container

**Comment by aleku399** [comment]
it could be better to know which form each person is working on

**Comment by epicallan** [comment]
I will assign the tasks.
